[build]
  command = "npm run build"
  publish = "dist/instant-cost-estimator"

# SPA fallback so client-side routes work on refresh/direct links
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
